runtime: php82 # Replace with php74 to use PHP 7.4

runtime_config: 
  document_root: .


automatic_scaling:
  target_cpu_utilization: 0.80
  target_throughput_utilization: 0.80
  min_instances: 1
  max_instances: 5
  cool_down_period_sec: 60

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|js|svg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js|svg|ico)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto

entrypoint:
  serve handler.php

env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: rt_digital
  CLOUDSQL_PASSWORD: IF@k9ls?l[?g2)K#
  CLOUDSQL_DSN: /cloudsql/rt-digital-402110:us-west1:rt-digital